### ISSUE TITLE
phpcov 8.0.0 exception

### ISSUE THREAD

**Issue by baptistedonaux** [sebastianbergmann/phpcov#99]
I can't determine what's the problem but when I try to generate coverage with phpcov 8.0.0 with report generated by PHPUnit 9.2 and 9.3, an exception is thrown.

```
$ phpunit --coverage-php ./coverage/foo.cov .
$ phpcov merge --text=report ./coverage
phpcov 8.0.0 by Sebastian Bergmann.

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function SebastianBergmann\CodeCoverage\CodeCoverage::__construct(), 0 passed in /home/docker/coverage/foo.cov on line 2 and exactly 2 expected in phar:///home/docker/phpcov/phpunit/php-code-coverage/src/CodeCoverage.php:133
Stack trace:
#0 /home/docker/coverage/foo.cov(2): SebastianBergmann\CodeCoverage\CodeCoverage->__construct()
#1 phar:///home/docker/phpcov/src/cli/Application.php(159): include('/home/docker/co...')
#2 phar:///home/docker/phpcov/src/cli/Application.php(65): SebastianBergmann\PHPCOV\Application->merge(Object(SebastianBergmann\PHPCOV\Arguments))
#3 /home/docker/phpcov(795): SebastianBergmann\PHPCOV\Application->run(Array)
#4 {main}
  thrown in phar:///home/docker/phpcov/phpunit/php-code-coverage/src/CodeCoverage.php on line 133

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SebastianBergmann\CodeCoverage\CodeCoverage::__construct(), 0 passed in /home/docker/coverage/foo.cov on line 2 and exactly 2 expected in phar:///home/docker/phpcov/phpunit/php-code-coverage/src/CodeCoverage.php on line 133

ArgumentCountError: Too few arguments to function SebastianBergmann\CodeCoverage\CodeCoverage::__construct(), 0 passed in /home/docker/coverage/foo.cov on line 2 and exactly 2 expected in phar:///home/docker/phpcov/phpunit/php-code-coverage/src/CodeCoverage.php on line 133

Call Stack:
    0.0039     557472   1. {main}() /home/docker/phpcov:0
    0.0297    1008792   2. SebastianBergmann\PHPCOV\Application->run() /home/docker/phpcov:795
    0.0309    1084616   3. SebastianBergmann\PHPCOV\Application->merge() phar:///home/docker/phpcov/src/cli/Application.php:65
    0.0347    1429912   4. include('/home/docker/coverage/foo.cov') phar:///home/docker/phpcov/src/cli/Application.php:159
    0.0358    1497952   5. SebastianBergmann\CodeCoverage\CodeCoverage->__construct() /home/docker/coverage/foo.cov:2

Dump $_GET
Dump $_POST

Variables in local scope (#5):
  $driver = *uninitialized*
  $filter = *uninitialized*
```

Works with phpcov 7.0.2

**Comment by sebastianbergmann** [comment]
Duplicate of https://github.com/sebastianbergmann/php-code-coverage/issues/792#issuecomment-672567394
